PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
    "id"                    TEXT PRIMARY KEY NOT NULL,
    "checksum"              TEXT NOT NULL,
    "finished_at"           DATETIME,
    "migration_name"        TEXT NOT NULL,
    "logs"                  TEXT,
    "rolled_back_at"        DATETIME,
    "started_at"            DATETIME NOT NULL DEFAULT current_timestamp,
    "applied_steps_count"   INTEGER UNSIGNED NOT NULL DEFAULT 0
);
INSERT INTO _prisma_migrations VALUES('38bd1b54-4c7a-4511-9e35-42878e8c78c4','cd5a8c0cdcdce768fca1cb04ea4862c0dc010e74dfd233bfb42e9d267f7fc6b3',1735602515191,'20241010142839_init',NULL,NULL,1735602515189,1);
INSERT INTO _prisma_migrations VALUES('3483083b-fe11-4009-9e3d-5d2699e8d70b','60bd3ff6b072432a0ada2d6f22e1f37846a520c0176109315150bb67a9e620cc',1735602515192,'20241010175642_education_model',NULL,NULL,1735602515191,1);
INSERT INTO _prisma_migrations VALUES('dde4370d-37a6-48f8-aed1-ac924128e66c','362d466aff984ddba7bbfbf681d566a905fc4356fc311a17af82033f3ecd9b1d',1735602515193,'20241220014025_add_new_table',NULL,NULL,1735602515192,1);
INSERT INTO _prisma_migrations VALUES('1c618baa-4e48-4bdd-b91d-578378b68b73','2dda3dacb18e436e02614a83ddc274898fad2448c42cb0a02c7f845ec397d8d9',1735602515195,'20241220014459_update_my_table',NULL,NULL,1735602515193,1);
INSERT INTO _prisma_migrations VALUES('6af522de-5a93-4fd4-9a59-e10ab922b85e','26eb69def1bcba8476427587d5d274385c0f5a65ad1e8ed89834b90d5c3ddf2e',1735602515197,'20241223153709_added_button_table',NULL,NULL,1735602515195,1);
INSERT INTO _prisma_migrations VALUES('b33018a2-9ca7-4020-8d32-5f8d349b2898','718ef843017a958fb0e583ae93816e7fac9bf7e0946e2a35c33efb854b713811',1735602515199,'20241223154018_changed_variable_types',NULL,NULL,1735602515197,1);
INSERT INTO _prisma_migrations VALUES('573835e4-f626-4261-a6e3-d86ed8cf992e','020eab0b71f415eff3e64b74f14d4457401be98d128079805ab0b6f547ad7cd3',1735602515201,'20241223160005_migrate',NULL,NULL,1735602515200,1);
INSERT INTO _prisma_migrations VALUES('ed77fd17-81a9-44ce-8277-094131f712ec','1fa8db8cfe01dce9767c4e5acd2459d609f442d067f2f17ad50c445171b0c39c',1735602515203,'20241230234521_fixed_id',NULL,NULL,1735602515202,1);
INSERT INTO _prisma_migrations VALUES('f8de1da6-8fe6-4fca-9f72-475ed1b43b77','6f4961f7a17adae3c7bb75113eafc8fecf94a54b43b18849f1c6d85baad662bf',1735831539690,'20250102152539_added_more_stuff',NULL,NULL,1735831539686,1);
CREATE TABLE IF NOT EXISTS "Education" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "category" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "link" TEXT NOT NULL,
    "linkText" TEXT NOT NULL
);
INSERT INTO Education VALUES('cm5bp7lft00028oyeb07owag7','coursework','AP Physics','AP Physics','link ','link');
INSERT INTO Education VALUES('cm5j372wd0001uxcdm0r2d5f9','certifications','Computer Science Principles by YouScience','"Computer Science Principles introduces students to the breadth of the field of computer science. In this course, students will learn to design and evaluate solutions and to apply computer science to solve problems through the development of algorithms and programs. They will use data to discover new knowledge. Students will also explain how computing innovations and computing systems, including the Internet, work, explore their potential impacts, and contribute to a computing culture that is collaborative and ethical."','/certificates/Hayden_Karas_Computer_Science_Principles_May-29-2024.pdf','View Certification');
INSERT INTO Education VALUES('cm5j3dfzk0002uxcdrwrroz1b','certifications','Computer Programming I by YouScience','"The Computer Programming 1 industry certification exam assesses knowledge of foundational computer programming skills. Learners demonstrate their understanding to design, code, and test programs while applying mathematical concepts. Basic coding concepts and problem-solving skills are evaluated during the exam."','/certificates/Hayden_Karas_Computer_Programming_I_Oct-1-2024.pdf','View Certification');
INSERT INTO Education VALUES('cm5j3ille0003uxcdfirsefpq','certifications','Computer Programming 2 Python by YouScience','"This course introduces students to more advanced programming concepts. Students will learn to create more powerful programs within a specific programming language - Java, Python, C++, or C#."','/certificates/Hayden_Karas_Computer_Programming_2_Python_Oct-1-2024.pdf','View Certification');
INSERT INTO Education VALUES('cm5j3mq0t0004uxcdnwoh7x4q','certifications','Computer Programming Advanced by YouScience','"The Computer Programming, Advanced industry certification exam assesses advanced concepts in computer programming and software engineering. It reviews and builds on the concepts introduced in Computer Programming 1 and 2, focusing on dynamic data structures, advanced utilization of classes, and applications of recursion using mathematical concepts. The exam also evaluates learners'' understanding of the differences between various programming languages."','/certificates/Hayden_Karas_Computer_Programming_Advanced_Oct-4-2024.pdf','View Certification');
INSERT INTO Education VALUES('cm5j41iqc0005uxcd45a7lase','awards','Jae S Lim Award for Mathematics','"Jae S. Lim Math & Science Scholarship aims to push the students in maths and science and make a career in the same field. They focus on providing the required support to all such students to accomplish their goals. They believe that these subjects are mainly responsible for developing the country and providing good assistance to students interested in these subjects will create a bright future for the country."','https://cranstononline.com/stories/cranston-high-school-west-celebrates-national-honor-society-inductees-and-academic-award-recipients,250318','View Article');
INSERT INTO Education VALUES('cm5j4j5by0006uxcddv04vs5a','courses','CS50x by Harvard','"Harvard University''s introduction to the intellectual enterprises of computer science and the art of programming for majors and non-majors alike, with or without prior programming experience. An entry-level course taught by David J. Malan, CS50x teaches students how to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development. Languages include C, Python, SQL, and JavaScript plus CSS and HTML. Problem sets inspired by real-world domains of biology, cryptography, finance, forensics, and gaming. The on-campus version of CS50x , CS50, is Harvard''s largest course."','/certificates/CS50x.jpg','View Certificate');
INSERT INTO Education VALUES('cm5j4y9wb0007uxcdn9974iw2','courses','"The Complete 2024 Web Development Bootcamp"','Online course that covered everything needed to start becoming a web developer. From beginning HTML and CSS to React, Node, and Express. Covered both front end and back end, as well as databases.','https://www.udemy.com/course/the-complete-web-development-bootcamp/?course_id=1565838&couponCode=NEWYEARCAREER','View Course');
CREATE TABLE IF NOT EXISTS "Skills" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "category" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL
);
INSERT INTO Skills VALUES('cm5bp88nc00038oye1n3msq89','languages','C#','I use C# to create video games with Unity. I''ve used Unity since 6th grade to make 2D and 3D games, and have placed top 10 nationally for multiple game development competitions using Unity and C#.');
INSERT INTO Skills VALUES('cm5fmk5mu00168o28pw7ifsl2','coursework','1','2');
INSERT INTO Skills VALUES('cm5for3a300198o28j19xsssg','languages','Java','I learned Java while self-studying for the AP CSA exam. I used Java to learn object-oriented programming and inheritance and created multiple small projects with it to study for the exam.');
INSERT INTO Skills VALUES('cm5gwnipk001l8o283t1e36bh','languages','JavaScript','I use Javascript for back-end and front-end web development. I use it alongside NodeJS, NextJS, and front-end html/react to create web applications. I''ve used Javascript since 9th grade.');
INSERT INTO Skills VALUES('cm5h1nead001m8o28rr5i3mjq','languages','Python','Python was the first programming language I used. I learned advanced python with Harvard''s CS50x course and took a class at my local college in python as well.');
INSERT INTO Skills VALUES('cm5h1oxen001n8o28uuqrh9du','languages','C','I learned C from Harvard''s CS50x online course and used it to complete challenges and create projects for the course. I use C when computing large numbers quickly, such as creating a prime number generator.');
INSERT INTO Skills VALUES('cm5h1rqd2001o8o28ed5f6gaj','languages','HTML/CSS','As a web developer, I have used HTML and CSS for countless projects. I am fluent in both languages and use them daily. I first learn them in 6th grade and have taken multiple courses that cover these languages.');
INSERT INTO Skills VALUES('cm5h1sqhb001p8o28s5v0lsxm','languages','SQL','I use SQL databases like SQLite3 to create local databases for web applications and websites. I learned SQL in CS50 and have used it multiple times since then.');
INSERT INTO Skills VALUES('cm5h1ufvs001q8o2885fppl7q','frameworks','NextJS','I learned NextJS by taking two Udemy courses covering NextJS and ReactJS. I used NextJS to create my personal website and am using it to create multiple future websites.');
INSERT INTO Skills VALUES('cm5h1vtu9001r8o281wm5j8vr','frameworks','Tailwind','I use Tailwind CSS alongside NextJS to make development fast, efficient, and easy. I like Tailwind because of its ease of use and customizability.');
INSERT INTO Skills VALUES('cm5h1xp5e001s8o285pjn8ikw','frameworks','NodeJS','When not using NextJS, I use node for the backend of my web apps, which links databases and APIs together for functionality within the web page. I''ve used Node to create multiple websites in the past but have not used it since learning Next.');
INSERT INTO Skills VALUES('cm5h20wo4001t8o28wzwen3en','frameworks','ExpressJS','I use ExpressJS to make working with Node easier and faster. I learned Express and Node at the same time and build all my Node web apps with Experess.');
INSERT INTO Skills VALUES('cm5h2261r001u8o285mcw3eim','frameworks','JQuery','I use JQuery when working within the backend to make altering front-end elements easier. I use JQuery when working with Express and Node and learned them all simultaneously.');
INSERT INTO Skills VALUES('cm5h23ug2001v8o28z830kppn','frameworks','Flask','I learned Flask through Harvard''s CS50x online course and use it as my backend when working with Python instead of Javascript. I used it to create my final project for CS50, but I don''t tend to use it anymore as I prefer JS.');
INSERT INTO Skills VALUES('cm5h29uak001w8o28vthvm0w9','skills','Math','As the captain of my school''s math team, I have won numerous awards in mathematics. I''ve completed Calculus and Statistics and am consistently looking for new challenges. I''ve scored the highest in my school two years in a row and received a perfect math score on the PSAT and a 790 on the SAT.');
INSERT INTO Skills VALUES('cm5h2bv0v001x8o2829qsi97l','skills','Physics','I love physics. I''ve taken AP Physics 1 and currently self-studying AP Physics E&M. I scored a 5 on the physics exam and interned at Brown University''s physics department. I use physics in game development by simulating them for 3D games.');
INSERT INTO Skills VALUES('cm5h2d394001y8o2821a9usp0','skills','Statistics','After taking AP Statistics, recieving a 5 on the exam, and using my statistical knowledge at my Brown University internship, I''m confident in my ability to determine statistical significance, create intervals, create samples, and determine bias.');
INSERT INTO Skills VALUES('cm5h2qqoe001z8o28265ke1ic','skills','Leadership','As the captain of my school''s math team and leader of our SkillsUSA game development team, I have experienced leadership in many areas. I''ve tutored and guided our math team to top 4 in the state, and lead our Game Dev team to top 10 nationally two years in a row.');
INSERT INTO Skills VALUES('cm5h2strq00208o28fpfta834','skills','Game Dev.','Working with Unity since 6th grade, Game Development is a hobby of mine. It has improved my CS and software engineering skills and taught me how to mix coding with other disciplines like physics and math. Getting top 10 nationally two years in a row with game dev, I am proficient in Unity.');
CREATE TABLE IF NOT EXISTS "Projects" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "urlTitle" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "descriptions" TEXT NOT NULL,
    "images" TEXT NOT NULL,
    "links" TEXT NOT NULL,
    "technologies" TEXT NOT NULL DEFAULT '[]',
    "type" TEXT NOT NULL DEFAULT 'website',
    "date" TEXT NOT NULL DEFAULT 'undefined'
);
INSERT INTO Projects VALUES('cm5bp10d300008oyevb73aytj','deanlaurowebsite','Dean Lauro Website','{"Description": "The Dean Lauro website is a modern and fully responsive platform designed to showcase his musical journey, portfolio, and professional updates. Using Node.js and Express as the backend framework, the site dynamically renders pages with EJS templates. The integration of SQLite ensures efficient management of database-driven content, while HTML, CSS, and JavaScript provide a visually appealing and interactive frontend. Mailtrap was incorporated for secure and reliable email testing, making the contact forms robust. The website is optimized for performance and offers an engaging user experience.", "Development": "Building the website presented several challenges, including designing a responsive layout that catered to various screen sizes and implementing a secure yet functional email testing system with Mailtrap. Optimizing the SQLite database for rapid content retrieval required thoughtful structuring of data and queries. Integrating EJS templates to render dynamic content seamlessly across pages also demanded precise coding to ensure efficiency. Despite these challenges, the end result is a website that balances functionality, performance, and aesthetics."}','["favicon.png", "homepage.jpg", "code.jpg", "contact.jpg", "project.jpg"]','[{"link": "https://github.com/DTYoda/DeanLauroWebsite", "title": "GitHub"},{"link": "https://www.deanlauro.com", "title": "DeanLauro"}]','[{"link": "hhttps://nodejs.org/en", "title": "NodeJS"}, {"link": "https://www.sqlite.org/", "title": "SQLite"}, {"link": "https://mailtrap.io/", "title": "MailTrap"}, {"link": "https://ejs.co/", "title": "EJS"}]','Website','September 2024');
INSERT INTO Projects VALUES('cm5rg8b3h00008o1n7phtq0oe','andromeda','Andromeda','{   "Game": "Andromeda is a first-person, open-world RPG set in the vast Andromeda Galaxy. Players step into the shoes of Kendrick, a space cadet who crash-lands on an alien planet while on a dangerous mission to support his family. The game challenges players to explore nine unique planets, each with distinct themes, enemies, and objectives. With an engaging storyline and the opportunity to upgrade spacesuits and spacecraft, Andromeda delivers an immersive experience for sci-fi and RPG enthusiasts. Its low-poly art style adds a charming aesthetic to the intergalactic adventure.",   "Development": "As the lead developer, I spearheaded the creation of Andromeda, taking charge of the coding and programming. I wrote all game scripts in C#, implementing advanced mechanics like GPU instancing, occlusion culling, and physics tailored for spherical planets. I integrated Unity features such as Shader Graph, Cinemachine, and the Universal Render Pipeline to optimize gameplay and visual fidelity. Beyond programming, I managed the version control system via GitHub, ensuring smooth collaboration and clean code. My leadership extended to coordinating team milestones and maintaining the project’s timeline and technical standards.",   "Competition": "Andromeda was submitted to the prestigious SkillsUSA Interactive Game and App Design competition. Competing at the Rhode Island state level, the game achieved first place, earning the team a spot in the national competition. At the national stage, Andromeda placed 8th, standing out among entries from across the country. The recognition validated the creative and technical efforts put into the project and highlighted its ability to compete with some of the best student-made games in the nation." }','[   "AndromedaIcon.jpeg",   "screenshot1.jpg",   "screenshot2.jpg",   "screenshot3.jpg",   "screenshot4.jpg",   "screenshot5.jpg",   "screenshot6.jpg",   "poster1.png",     "poster3.png",   "conceptart.png",   "event1.JPG",   "event2.jpeg",   "event3.jpeg" ]','[{"link": "https://github.com/DTYoda/Andromeda", "title": "GitHub"}, {"link": "https://youtu.be/V7SX8VqHUc8", "title": "YouTube"}, {"link": "https://docs.google.com/document/d/1I2XoH_qX1y0xyQi8ctNzDlU5seFClQ7eOkVecfUQuFo/edit?usp=sharing", "title": "Docs"}]','[   {     "title": "Unity",     "link": "https://unity.com/"   },   {     "title": "CSharp",     "link": "https://learn.microsoft.com/en-us/dotnet/csharp/"   },   {     "title": "Blender",     "link": "https://www.blender.org/"   },   {     "title": "PhotoShop",     "link": "https://www.adobe.com/products/photoshop.html"   } ]','Video Game','September 2023-July 2024');
DELETE FROM sqlite_sequence;
COMMIT;
