import "./globals.css";
import Navigation from "@/_components/navigation";

export const metadata = {
  title: "Hayden Karas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex-1 flex-col">
        <Navigation />
        <main className="max-w-7xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
